apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: sns
type: Opaque
data:
  SMTP_USER: QUtJQVEzRUdXSUlJSkNGS0pRUUI=
  SMTP_PASSWORD: QkpCWDgzTGFBR21zM0ZSSzdEakJqTFpLSUZpMzk2cTJOa3A0aSs3RzBOK3o=
