server:
  shutdown: immediate
sns:
  user-server: http://user-service.sns.svc.cluster.local:8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns
    username: sns-server
    password: 12345678

